### ISSUE TITLE
processing mascot results throws error in "processing scan file 0" stage

### ISSUE THREAD

**Issue by martinPasen** [QuantSysBio/inSPIRE#6]
error message:

2022-11-03 16:34:51.227727: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: 
CUDA_ERROR_UNKNOWN: unknown error
        Models already downloaded.
        Formatted Prosit input written.
2/2 [==============================] - 2s 185ms/step
2/2 [==============================] - 3s 310ms/step
        MS Search Results ready.
        Basic Features added, adding Spectral Features.
                Processing scan file 0.
Traceback (most recent call last):
  File "/home/martin.pasen/Code/prosit-library-reanalises/run_inspire.py", line 56, in <module>
    run_inspire(config_path)
  File "/home/martin.pasen/Code/prosit-library-reanalises/run_inspire.py", line 47, in run_inspire
    create_features(config)
  File "/home/martin.pasen/Code/prosit-library-reanalises/.venv/lib/python3.8/site-packages/inspire/feature_creation.py", line 603, in create_features
    write_rescoring_features(
  File "/home/martin.pasen/Code/prosit-library-reanalises/.venv/lib/python3.8/site-packages/inspire/feature_creation.py", line 514, in write_rescoring_features
    write_with_spectral_features(
  File "/home/martin.pasen/Code/prosit-library-reanalises/.venv/lib/python3.8/site-packages/inspire/feature_creation.py", line 227, in write_with_spectral_features
    process_single_file(
  File "/home/martin.pasen/Code/prosit-library-reanalises/.venv/lib/python3.8/site-packages/inspire/feature_creation.py", line 321, in process_single_file
    scan_df = process_mgf_file(
  File "/home/martin.pasen/Code/prosit-library-reanalises/.venv/lib/python3.8/site-packages/inspire/input/mgf.py", line 44, in process_mgf_file
    with mgf.read(mgf_filename) as reader:
  File "/home/martin.pasen/Code/prosit-library-reanalises/.venv/lib/python3.8/site-packages/pyteomics/mgf.py", line 458, in read
    return tp(*args, **kwargs)
  File "/home/martin.pasen/Code/prosit-library-reanalises/.venv/lib/python3.8/site-packages/pyteomics/mgf.py", line 290, in __init__
    super(IndexedMGF, self).__init__(source, parser_func=self._read, pass_file=False, args=(), kwargs={},
  File "/home/martin.pasen/Code/prosit-library-reanalises/.venv/lib/python3.8/site-packages/pyteomics/mgf.py", line 131, in __init__
    super(MGFBase, self).__init__(source, **kwargs)
  File "/home/martin.pasen/Code/prosit-library-reanalises/.venv/lib/python3.8/site-packages/pyteomics/auxiliary/file_helpers.py", line 1020, in __init__
    super(TaskMappingMixin, self).__init__(*args, **kwargs)
  File "/home/martin.pasen/Code/prosit-library-reanalises/.venv/lib/python3.8/site-packages/pyteomics/auxiliary/file_helpers.py", line 380, in __init__
    super(TimeOrderedIndexedReaderMixin, self).__init__(*args, **kwargs)
  File "/home/martin.pasen/Code/prosit-library-reanalises/.venv/lib/python3.8/site-packages/pyteomics/auxiliary/file_helpers.py", line 401, in __init__
    super(IndexedTextReader, self).__init__(source, mode='rb', encoding=None, **kwargs)
  File "/home/martin.pasen/Code/prosit-library-reanalises/.venv/lib/python3.8/site-packages/pyteomics/auxiliary/file_helpers.py", line 199, in __init__
    self.reset()
  File "/home/martin.pasen/Code/prosit-library-reanalises/.venv/lib/python3.8/site-packages/pyteomics/auxiliary/file_helpers.py", line 204, in reset
    self._source = _file_obj(self._source_init, self._mode, self._encoding)
  File "/home/martin.pasen/Code/prosit-library-reanalises/.venv/lib/python3.8/site-packages/pyteomics/auxiliary/file_helpers.py", line 102, in __init__
    self.file = codecs.open(f, mode, encoding)
  File "/usr/lib/python3.8/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'data/prosit1/measurements/01974c_BA1-TUM_missing_first_1_01_01-2xIT_2xHCD-1h-R4/controllerType=0 controllerNumber=1 scan=32948.mgf'

**Comment by jamc1996** [comment]
Hi Martin,

Thanks for pointing it out. We were assuming mascot users would be using mscovert with the scan title editted to include the source name but we should have insure it would work for the default settings.

The PR linked should address the issue, you should be able to install the tarball attached also if you want to get moving before it's merged and published on pip.

[inspirems-1.1.tar.gz](https://github.com/QuantSysBio/inSPIRE/files/9931139/inspirems-1.1.tar.gz)

Thanks for using inSPIRE!

Best wishes,
John.

**Comment by martinPasen** [comment]
Thanks for the fast response. The problem seems to prevail even after implementing the proposed changes.

**Comment by jamc1996** [comment]
For anyone reading this in future we were able to resolve this issue. I have deleted the tar file from the earlier message. The 
corrected file is:
```
[inspirems-1.1.tar.gz](https://github.com/QuantSysBio/inSPIRE/files/9938161/inspirems-1.1.tar.gz)
```
However, it should be published on pip in the next few days and calling
```
pip install inspirems
```
will automatically download version 1.1.

**Comment by jamc1996** [comment]
Version bump is now published on pypi so the default
```
pip install inspirems
```
should download the correct version.

If you are experiencing this issue and already have inspirems==1.0 install please call

```
pip install inspirems --upgrade
```

Thanks Martin for raising this issue!
